spring:
  application:
    name: culture-weave-backend
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB  # 单个文件最大大小
      max-request-size: 10MB  # 单次请求最大大小
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${culture-weave.spring.datasource.host}:${culture-weave.spring.datasource.port}/culture_weave?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${culture-weave.spring.datasource.username}
    password: ${culture-weave.spring.datasource.password}

server:
  port: 8123
#  servlet:
#    context-path: /api

# mybatis-plus 相关配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: false    # MyBatis 下划线转驼峰
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 启用 SQL 运行器
    enable-sql-runner: true
    db-config:
      logic-delete-field: is_delete  # 全局逻辑删除
      logic-delete-value: 1    # 逻辑删除值（默认为1）
      logic-not-delete-value: 0  # 逻辑未删除值（默认为0）

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zzx.cultureweavebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


